import React, {useState} from "react";
import LocationPicker from "../../components/Location/LocationPicker";
import NativePickerField from "../../components/Form/NativePickerField";
import {NigerianStates} from "../../services/states";
import banks from "../../services/banks";
import {resolveVendorBankAccount, getVendorOnboardingErrorMessage} from "../../services/vendorOnboarding";

const labels = {shopName:"Shop name",description:"Description",coverImageUrl:"Store image",categories:"Categories",socialMediaHandle:"Social links",Address:"Delivery address",deliveryMode:"Delivery options",pickupAddress:"Pickup address",bankDetails:"Payout account",idVerification:"Identity document"};
export default function VendorCorrections({review, vendorData, setVendorData, categories, bankDetails, setBankDetails, deliveryMode, handleDeliveryModeChange, idVerification, handleIdVerificationChange, handleImageUpload, handleIdImageUpload, isIdImageUploading, isCoverImageUploading, isLoading, onSupport}) {
  const [resolving,setResolving]=useState(false),[error,setError]=useState("");
  const inputClass="w-full rounded-xl border border-orange-100 bg-white p-3 text-sm text-gray-900";
  const change=(key,value)=>setVendorData(v=>({...v,[key]:value}));
  const pickup=<LocationPicker initialAddress={vendorData.pickupAddress} initialCoords={{lat:vendorData.pickupLat,lng:vendorData.pickupLng}} onLocationSelect={({address,lat,lng})=>setVendorData(v=>({...v,pickupAddress:address,pickupLat:lat,pickupLng:lng}))}/>;
  return <div className="mx-auto max-w-xl space-y-5 px-4 pb-12"><h1 className="text-2xl font-bold text-gray-950">Update your application</h1><p className="text-sm leading-6 text-gray-600">{review.reason}</p><p className="text-sm leading-6 text-gray-600">Your other submitted details are saved. Update the items below and send them for review.</p>{review.suggestions&&<p className="rounded-xl bg-orange-50 p-4 text-sm">{review.suggestions}</p>}
    <fieldset disabled={isLoading||isIdImageUploading||isCoverImageUploading||resolving} className="space-y-5">
    {review.fields.map(f=><section key={f.key} className="space-y-3 rounded-2xl border border-orange-100 bg-white p-4"><h2 className="font-semibold text-gray-950">{labels[f.key]}</h2><p className="text-sm text-gray-600">{f.reason}</p>
      {f.key==="shopName"&&<input aria-label="Shop name" required className={inputClass} value={vendorData.shopName||""} onChange={e=>change("shopName",e.target.value)}/>}
      {f.key==="description"&&<textarea aria-label="Store description" required maxLength={1000} rows={5} className={inputClass} value={vendorData.description||""} onChange={e=>change("description",e.target.value)}/>}
      {f.key==="coverImageUrl"&&<>{vendorData.coverImageUrl&&<img src={vendorData.coverImageUrl} alt="Your store" className="h-40 w-40 rounded-xl object-cover"/>}<input aria-label="Replace store image" type="file" accept="image/*" onChange={handleImageUpload}/><p role="status" className="text-xs">{isCoverImageUploading?"Uploading image…":"Choose a clear store image."}</p></>}
      {f.key==="categories"&&<NativePickerField name="categories" title="Categories" value={vendorData.categories||[]} options={categories} multiple onChange={v=>change("categories",v)} className={inputClass}/>}
      {f.key==="socialMediaHandle"&&["instagram","facebook","tiktok","twitter"].map(network=><label className="block text-sm" key={network}>{network}<input type="url" className={inputClass} value={vendorData.socialMediaHandle?.[network]||""} onChange={e=>setVendorData(v=>({...v,socialMediaHandle:{...v.socialMediaHandle,[network]:e.target.value}}))}/></label>)}
      {f.key==="Address"&&<><LocationPicker initialAddress={vendorData.Address} initialCoords={vendorData.location} onLocationSelect={({address,lat,lng})=>setVendorData(v=>({...v,Address:address,location:{lat,lng}}))}/><NativePickerField name="state" title="State" value={vendorData.state||""} options={NigerianStates} onChange={v=>change("state",v)} className={inputClass}/></>}
      {f.key==="deliveryMode"&&<><NativePickerField name="deliveryMode" title="Delivery options" value={deliveryMode} options={["Delivery","Delivery & Pickup"]} onChange={handleDeliveryModeChange} className={inputClass}/>{deliveryMode==="Delivery & Pickup"&&pickup}</>}
      {f.key==="pickupAddress"&&pickup}
      {f.key==="bankDetails"&&<><NativePickerField name="bank" title="Bank" value={bankDetails.bankCode||""} options={banks.map(b=>({label:b.name,value:b.code}))} onChange={code=>{const b=banks.find(b=>b.code===code);setBankDetails(v=>({...v,bankCode:code,bankName:b?.name||"",accountName:""}));}} className={inputClass}/><input aria-label="Bank account number" className={inputClass} inputMode="numeric" maxLength={10} value={bankDetails.accountNumber||""} onChange={e=>setBankDetails(v=>({...v,accountNumber:e.target.value.replace(/\D/g,""),accountName:""}))}/><button type="button" className="rounded-xl border border-orange-200 p-3 text-sm" onClick={async()=>{setResolving(true);setError("");try{const r=await resolveVendorBankAccount(bankDetails);setBankDetails(v=>({...v,accountName:r.accountName}));}catch(e){setError(getVendorOnboardingErrorMessage(e,"Unable to verify this account."));}finally{setResolving(false);}}}>Verify account</button><p className="text-sm">{bankDetails.accountName||"Verify the account before submitting."}</p></>}
      {f.key==="idVerification"&&<><NativePickerField name="idVerification" title="Identity document type" value={idVerification} options={["NIN","International Passport","CAC","School ID","Work ID"]} onChange={handleIdVerificationChange} className={inputClass}/><input aria-label="Replace identity document" type="file" accept="image/*" onChange={handleIdImageUpload}/><p role="status" className="text-xs">{isIdImageUploading?"Uploading securely…":vendorData.idUploaded?"Document recorded. Upload a replacement if requested.":"Upload your identity document."}</p></>}
    </section>)}
    {error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button type="submit" className="w-full rounded-xl bg-customOrange p-3 font-semibold text-white disabled:opacity-50">{isLoading?"Submitting changes…":"Resubmit for review"}</button>
    </fieldset><button type="button" onClick={onSupport} className="text-sm font-semibold text-customOrange">Contact support</button>
  </div>;
}
